# release.yml

# workflow 's name
name: Build electron App for Mac

on:
  push:
    branches: ['main']

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      # check out repository
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # create electron-builder.json
      - name: Create and populate electron-builer.json、notarize.js、.p12 file
        env:
          APPLE_NOTARIZE: ${{ secrets.APPLE_NOTARIZE }}
          ELE_BUILER_MAC: ${{ secrets.ELE_BUILER_MAC }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          P12: ${{ secrets.P12 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        shell: bash
        run: |
          echo $ELE_BUILER_MAC > electron-builer.json
          echo $APPLE_NOTARIZE > notarize.js

          P12FILE=$RUNNER_TEMP/build_certificate.p12
          echo -n "$P12" | base64 --decode --output $P12FILE

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $P12FILE -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      # install & build app for mac
      - run: yarn install --frozen-lockfile
      - run: yarn global add @angular/cli
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
